### ISSUE TITLE
How do you register a custom action invoker?

### ISSUE THREAD

**Issue by mwpowellhtx** [autofac/Autofac.Mvc#17] opened 2017-01-17 00:10 UTC
Hello,

On a more practical front, how are filter dependencies injected?

I'd done something along these lines based on Castle Windsor, but I had to replace the [``IActionInvoker``](http://msdn.microsoft.com/en-us/library/system.web.mvc.iactioninvoker.aspx) based on [``ControllerActionInvoker``](http://msdn.microsoft.com/en-us/library/system.web.mvc.controlleractioninvoker.aspx) in order to do so.

This, and a possibly couple of other services, potentially provided via, in this case, the ``AutofacDependencyResolver``.

For example,

```C#
using System.Linq;
using System.Web.Mvc;

namespace Kingdom.Web.Mvc
{
    using Castle.Windsor;

    public class WindsorControllerActionInvoker : ControllerActionInvoker, IWindsorActionInvoker
    {
        private IWindsorContainer Container { get; }

        public WindsorControllerActionInvoker(IWindsorContainer container)
        {
            Container = container;
        }

        private void InjectFilter<T>(T obj)
        {
            // InjectObject is an extension method of mine, basically handles the reflection, introspection, and property setters; fairly standard looking stuff
            Container.InjectObject(obj);
        }

        protected override FilterInfo GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
        {
            var filterInfo = base.GetFilters(controllerContext, actionDescriptor);

            // We must treat each of the Filter types individually.
            filterInfo.AuthorizationFilters.ToList().ForEach(InjectFilter);
            filterInfo.ActionFilters.ToList().ForEach(InjectFilter);
            filterInfo.ResultFilters.ToList().ForEach(InjectFilter);
            filterInfo.ExceptionFilters.ToList().ForEach(InjectFilter);

            return filterInfo;
        }
    }
}
```

Thanks!

**Comment by mwpowellhtx** [comment] 2017-01-17 00:15
Reviewing the code for *"actioninvoker"*, I see two hits, one in registration methods, and another in the tests. So, do I interpret that correctly, and there are hooks, but it is up the end user to provide a custom action invoker?

```C#
public static IRegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle>
    InjectActionInvoker<TLimit, TActivatorData, TRegistrationStyle>(
        this IRegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle> registrationBuilder);

public static IRegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle>
    InjectActionInvoker<TLimit, TActivatorData, TRegistrationStyle>(
        this IRegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle> registrationBuilder,
        Service actionInvokerService);
```

**Comment by mwpowellhtx** [comment] 2017-01-17 00:16
Follow on comment, in my case, I'd like for the action invoker to be factory created by the container, especially since there may be resources constructor injected into the invoker.

**Comment by mwpowellhtx** [comment] 2017-01-17 00:27
Another consideration, I don't know, perhaps ``InjectActionInvoker(...)`` is an artifact of previous version(s) of *Mvc*. Today, I'm fairly certain that it can be resolved from the *Dependency Resolver*. In *Castle Windsor* parlance, I register with the container as a *Transient*, though perhaps it could be *Singleton*, or nominally *Per Web Request*.

Registering a "service" seems like missing the point to me, especially given the fact that all you need to do is provide a customized (if customizable) implementation of *IActionInvoker*, potentially even derive from *ControllerActionInvoker*.

So...

The question becomes, is that something that the **Autofac.Integration.Mvc** can and/or should be doing?

**Comment by tillig** [comment] 2017-01-17 01:23
I'm confused about what you're asking here. The title of the issue is about injecting action filter parameters, [for which there is support, just not through an invoker](http://autofac.readthedocs.io/en/latest/integration/mvc.html#enable-property-injection-for-action-filters).

Then things switch to asking about how we register our action invoker, but you found that code so I'm guessing you can just read it to see how it works.

Then it looks like you want to register your own action invoker...?

If this is a "How do I do X with Autofac and MVC?" question, _please close this issue and ask on StackOverflow_. Tag with `autofac`. There is a huge community out there and chances are your question is already answered. If it's not, you'll get a more complete answer faster, and we project owners monitor that, too.

If it's a bug or enhancement request, can you clarify what you're looking for?

Thanks!

**Comment by mwpowellhtx** [comment] 2017-01-17 03:48
@tillig Sorry for the confusion. I am asking about injecting a custom *action invoker*.

Is there utility using the registration methods you provide through *Autofac Mvc*?

Or should I just register with Autofac?

**Comment by tillig** [comment] 2017-01-17 04:01
```csharp
builder.RegisterType<MyActionInvoker>().As<IActionInvoker>();
builder.RegisterControllers().InjectActionInvoker();
```

The first line makes your action invoker the default service resolved for the invoker; the second line handles ensuring that the `IActionInvoker` is resolved and attached to the controller correctly.

[Here's a unit test showing it.](https://github.com/autofac/Autofac.Mvc/blob/21ee30c7e50255dce26ea6ce4725ec8c38917769/test/Autofac.Integration.Mvc.Test/RegistrationExtensionsFixture.cs#L404)

**Closed as completed by tillig** 2017-01-17 04:01 UTC

**Comment by mwpowellhtx** [comment] 2017-01-17 04:20
I wondered about that, thank you.
