### ISSUE TITLE
Get a can not load assembly "System.Web.Mvc, Version=5.1.0.0" error when i put project in a directory name contain "#"

### ISSUE THREAD

**Issue by lin2code** [autofac/Autofac.Mvc#14] opened 2016-10-25 05:50 UTC
I'm using Autofac.Mvc 4.0.0.0 and my ASP.NET MVC version is 5.2.3.0. I create a project on desktop, using   Autofac it's work. when i copy this project to my project folder(which contain "#") it's get this error.  
First I thought this a config/nuget version/framework version/refrence problem. Then i try them all, still get this error. And the project build success but this error appear when the project run.  
Finally i found out this error only appear when i put the project in to the specific folder which name contain "#", then i realize it's maybe a Autofac bug. And why i get a error like this, it's nothing relate to a directory issue. Guess it just load 5.1.0.0 version when it try load assembly error.

**Comment by tillig** [comment] 2016-10-25 13:09
At first glance this sounds a lot more like a .NET assembly loader issue than something to do specifically with Autofac, but there's not enough information here to determine.

What is the full exception with stack trace? Do you have steps to reproduce the issue or a repro checked in somewhere we can see? Did this work before adding Autofac?

**Comment by tillig** [comment] 2016-10-25 13:25
It appears this was also [cross posted to StackOverflow](http://stackoverflow.com/q/40232535/8116), which means we'll need to follow up in two places.

**Comment by lin2code** [comment] 2016-10-25 14:00
I'm creating a mvc website development template. This is the project [MVCWebSite](https://github.com/631320085/MVCWebsite)  
**I put project in "#Test" like this**  
![qq 20161025211905](https://cloud.githubusercontent.com/assets/4160160/19688280/aec54bee-9afb-11e6-837a-534ddff8616d.png)  
Then get a exception 
![exceptioin](https://cloud.githubusercontent.com/assets/4160160/19688391/1411a59c-9afc-11e6-9ef5-de71d503d783.png)

**If i remove "#" it's work.**  

![qq 20161025212753](https://cloud.githubusercontent.com/assets/4160160/19688438/500c2608-9afc-11e6-98c0-7426677a4670.png)
![qq 20161025212849](https://cloud.githubusercontent.com/assets/4160160/19688437/4fff63c8-9afc-11e6-9fbb-6468c8876a35.png)  

**If add the "#" back, and comment Autofac register code, it's work again.**  
![qq 20161025211905](https://cloud.githubusercontent.com/assets/4160160/19688280/aec54bee-9afb-11e6-837a-534ddff8616d.png) 
![qq 20161025213248](https://cloud.githubusercontent.com/assets/4160160/19688676/42bce892-9afd-11e6-8f8d-1a921e7da46a.png)
![qq 20161025213306](https://cloud.githubusercontent.com/assets/4160160/19688684/44aeba4a-9afd-11e6-8237-aff61affa653.png)
![qq 20161025213320](https://cloud.githubusercontent.com/assets/4160160/19688688/470d53be-9afd-11e6-88e9-3ce6279bb0aa.png)

**Comment by lin2code** [comment] 2016-10-25 14:01
The question on StakOverflow is posted by me.

**Comment by tillig** [comment] 2016-10-25 16:56
Unfortunately, I'm unable to reproduce the issue.

What I did:
1. [Download the zip of your repo](https://github.com/631320085/MVCWebsite/archive/master.zip) and put it at `C:\dev\test\MVCWebSite`.
2. Open `C:\dev\test\MVCWebSite\MVCWebSite.sln` in Visual Studio 2015.
3. Update `DemoController` so it doesn't try to call a database because I don't have your MySQL instances.
4. Build and start the app - get the home page.
5. Close Visual Studio 2015.
6. Rename `C:\dev\test\MVCWebSite` to ``C:\dev\#test\MVCWebSite`.
7. Open `C:\dev\#test\MVCWebSite\MVCWebSite.sln` in Visual Studio 2015.
8. Build and start the app - get the home page.

Something I noticed that's odd about your error screen shot is that the paths for your app don't line up. For example, I see the error occurs in `D:\GitHub\MVCWebsite\MVCWebSite\MVCWebSite\Global.asax.cs` but the binding failure shows the application itself is in `D:\#Test\MVCWebSite\MVCWebSite`.

![The paths don't line up](https://cloud.githubusercontent.com/assets/1156571/19695428/169551ec-9a98-11e6-9499-f9506f49b5c2.png)

In other errors including binding errors the source file is generally in the application. For example, here's a clip of the error I see due to not having your databases:

![Path points to app code](https://cloud.githubusercontent.com/assets/1156571/19695506/6bab0500-9a98-11e6-8c2d-9c8ca9a16ce2.png)

This is a strong indicator that the problem isn't with Autofac so much as something you're doing - perhaps pre-compiling the base application and trying to refer to it as an assembly? Perhaps something in the way you're referencing code from a different location? The app is acting as though the binding redirects are potentially in `D:\GitHub\MVCWebsite\MVCWebSite\MVCWebSite\web.config` but not in `D:\#Test\MVCWebSite\MVCWebSite\web.config` or something similar.

Given I can't reproduce it and this is _very much_ a binding redirect problem since Autofac does not explicitly load assemblies (e.g., you won't find Autofac doing any `Assembly.Load` or `Assembly.LoadFrom` stuff - any on-the-fly assembly loading is occurring due to the .NET runtime), I'm going to conclude there's really nothing we can do here - it's a question for .NET runtime folks that is potentially machine or configuration specific to your setup.

If you are able to come up with a much smaller, much simpler reproduction (no "DAL," no "BLL," unless those things are _very specific to reproducing the issue_) and are able to reproduce it yourself on other machines, we can try re-opening and figuring it out. In the meantime, I'd look at what's happening in your app to cause the paths to the source files to be messed up.

**Closed as completed by tillig** 2016-10-25 16:56 UTC

**Comment by lin2code** [comment] 2016-10-25 17:37
The odd file path maybe a cache problem, I copy it from `D:\GitHub\MVCWebsite\MVCWebSite` then open run directly get the odd screen shot, so I remove all `obj` folders of this project and rebuilt it then get a exception like this.
![exception](https://cloud.githubusercontent.com/assets/4160160/19696844/7b7dcac0-9b1b-11e6-8e16-8d91dccf86fa.png)
Anyway it doesn't affect my work now, thanks a lot. I'll test it on other machine and continue figure it out, if found out anything may cause this will let you know.

**Comment by lin2code** [comment] 2016-10-26 02:17
Hi, i just reproduce it on another machine. And I know why you can't reproduce it. The reason is **`it's only appear when the "#" is the first char after drive letter`** eg `D:\#some\thing` or `C:\#some\thing`. Hope this will help you.

**Comment by lin2code** [comment] 2016-10-26 05:38
Finally, **I confirm it's a `assemblyBinding` bug**.  
- 1. Create a new solution in `D:\Test` with a mvc project `Testp` and a class library `Testc`.
- 2. Add Nuget pack `NewtonSoft.Json` version 9.0.0.0 to `Testp`, add `NewtonSoft.Json` version 8.0.0.0 to `Testc`.
- 3. Using NewtonSoft.Json in `Testc`, then using `Testc` in `Testp` to call NewtonSoft.Json's method.  

First run it will get an exception and warn you add `assemblyBinding` to web.config, when you added it, it's run success. Then change directory to `D:\#Test` , this exception jump out.  
So, turn out it's Microsoft's bug. I should report it to MS team instead of you, sorry for the inconvenience.
